version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: construction_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: construction_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: construction_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Optional: MinIO for local S3 development
  minio:
    image: minio/minio
    container_name: construction_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data: